export enum PrescriptionFormFields {
  patientFirstName = "patientFirstName",
  patientLastName = "patientLastName",
  patientStreet = "patientStreet",
  patientCity = "patientCity",
  patientState = "patientState",
  patientDOB = "patientDOB",
  prescriberLastName = "prescriberLastName",
  prescriberFirstName = "prescriberFirstName",
  prescriberStreet = "prescriberStreet",
  prescriberCity = "prescriberCity",
  prescriberState = "prescriberState",
  prescriberNPI = "prescriberNPI",
  issueDate = "issueDate",

  name = "name",
  strength = "strength",
  dosageForm = "dosageForm",
  quantity = "quantity",
  directions = "directions",
}
